services:
  frontend-web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    env_file:
      - ./frontend-web/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
